module.exports = {
  KYLE: "kyle",
  SUN: "Sun",
  GONI: "Goni",
  DOBI: "Dobi",
  ELLA: "Ella",
  DONGDONG: "Dongdong",
  SUNNY: "Sunny",
  BRAN: "Bran",
  SINSAE: "Sinsae",
  ZIG: "Zig",
  CHAFFE: "Chaffe",
  SIMBA: "Simba",
  PETER: "Peter",
  GROOMING: "Grooming",
  MIKI: "Miki",
  INCH: "Inch",
  CHRIS: "Chris",
  COLIN: "Colin",
  YUJO: "Yujo",
  DITO: "Dito",
  TYCHE: "Tyche",
  JUMO: "Jumo",
  FANO: "Fano",
  HARU: "Haru",
  BEUCCOL: "Beuccol",
};
